### ISSUE TITLE
Allow users to store their default values in a configuration file.

### ISSUE THREAD

**Issue by kent0** [thilinarmtb/NekBench#31]
For repeated use of NekBench, it becomes tedious to type out the command even with the added universal default values. The user should be able to assign variables in a file, let's say user.config, and NekBench will source that file before checking for required specification and running.

**Comment by kent0** [comment]
#51

**Comment by thilinarmtb** [comment]
Merged #51. I will keep this issue open in case we want to improve more on the
config file.

**Comment by thilinarmtb** [comment]
Closed by #51.
